name: "Build and populate cache"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - uses: cachix/cachix-action@v6
      with:
        name: mic92
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: |
        nix-build -A nix-build-uncached
        ./result/bin/nix-build-uncached non-broken.nix
