name: "Build and populate cache"
on:
  pull_request:
  push:
  schedule:
    # everyday at 2:51
    - cron:  '51 2 * * *'
jobs:
  tests:
    strategy:
      matrix:
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=https://github.com/Mic92/nixpkgs/archive/master.tar.gz
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Gerschtli/install-nix-action@ddf1cd2bc500fec5a443c8858214d79545cc5e2d
      with:
        NIX_PATH: ${{ matrix.nixPath }}
    - run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - uses: cachix/cachix-action@v6
      with:
        name: mic92
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: nix-build
      run: nix run -f . nix-build-uncached -c nix-build-uncached non-broken.nix
    - name: Trigger NUR update
      run: curl -XPOST "https://nur-update.herokuapp.com/update?repo=mic92"
   
